# Generated by Django 4.0.1 on 2022-12-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0003_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
